"use client";

import { AppSchema } from "@/instant.schema";
import { InstaQLEntity } from "@instantdb/react";
import { Trophy, ExternalLink, RotateCcw, ThumbsUp, Share, Download, FileCode } from "lucide-react";
import { useState } from "react";
import ShareLinkModal from "@/components/ui/ShareLinkModal";
import { useI18n } from "@/components/LanguageProvider";

type Room = InstaQLEntity<AppSchema, "rooms">;
type Player = InstaQLEntity<AppSchema, "players">;
type QueueItem = InstaQLEntity<AppSchema, "queue_items">;

interface SummaryViewProps {
  room: Room & { players: Player[]; queue_items: QueueItem[] };
}

export default function SummaryView({ room }: SummaryViewProps) {
  const { t, language } = useI18n();
  const [showLinkModal, setShowLinkModal] = useState(false);
  const [shareUrl, setShareUrl] = useState("");

  const playedSongs = room.queue_items
    .filter(q => q.status === "PLAYED" || q.status === "SKIPPED") // Include skipped songs
    .sort((a, b) => a.created_at - b.created_at);

  const calculateScore = (votes: any) => {
      if (!votes) return null;
      const values = Object.values(votes) as number[];
      if (values.length === 0) return null;
      const sum = values.reduce((a, b) => a + b, 0);
      return Math.round(sum / values.length);
  };

  const handleDownloadJSON = () => {
      const data = JSON.stringify(room, null, 2);
      const blob = new Blob([data], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `2mdj-session-${room.code}.json`;
      link.click();
      URL.revokeObjectURL(url);
  };

  const handleDownloadHTML = () => {
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>2-Minute DJ Session - ${room.code}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0a; color: #fff; padding: 40px 20px; line-height: 1.6; }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 2.5rem; text-align: center; margin-bottom: 10px; }
    .subtitle { text-align: center; color: #888; margin-bottom: 40px; font-size: 1.1rem; }
    .song { display: flex; align-items: center; gap: 16px; padding: 16px; background: #1a1a1a; border-radius: 12px; margin-bottom: 12px; border: 1px solid #333; }
    .song:hover { border-color: #6366f1; }
    .thumbnail { width: 80px; height: 60px; border-radius: 8px; object-fit: cover; background: #333; flex-shrink: 0; }
    .info { flex: 1; min-width: 0; }
    .title { font-weight: 600; font-size: 1rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
    .dj { color: #888; font-size: 0.875rem; }
    .score { padding: 6px 12px; border-radius: 8px; font-weight: 600; font-size: 0.875rem; }
    .score.good { background: rgba(34, 197, 94, 0.2); color: #22c55e; }
    .score.bad { background: rgba(239, 68, 68, 0.2); color: #ef4444; }
    .score.neutral { background: #333; color: #888; }
    .skipped { font-size: 0.65rem; background: rgba(239, 68, 68, 0.2); color: #ef4444; padding: 2px 8px; border-radius: 999px; margin-left: 8px; text-transform: uppercase; letter-spacing: 0.05em; }
    .link { color: #6366f1; text-decoration: none; padding: 8px; border-radius: 8px; background: #1a1a1a; }
    .link:hover { background: rgba(99, 102, 241, 0.2); }
    .index { width: 32px; height: 32px; border-radius: 50%; background: #262626; display: flex; align-items: center; justify-content: center; color: #888; font-size: 0.875rem; flex-shrink: 0; }
    .footer { text-align: center; margin-top: 40px; color: #666; font-size: 0.875rem; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🎧 Session Summary</h1>
    <p class="subtitle">${playedSongs.length} tracks shared • Room: ${room.code}</p>
    
    ${playedSongs.map((song, index) => {
      const score = calculateScore(song.votes);
      const scoreClass = score !== null ? (score > 75 ? 'good' : score < 25 ? 'bad' : 'neutral') : '';
      const player = (song as any).player;
      return `
    <div class="song">
      <div class="index">${index + 1}</div>
      <img class="thumbnail" src="https://img.youtube.com/vi/${song.video_id}/mqdefault.jpg" alt="" onerror="this.style.display='none'">
      <div class="info">
        <div class="title">${song.video_title || `Unknown Track (${song.video_id})`}${song.status === 'SKIPPED' ? '<span class="skipped">Skipped</span>' : ''}</div>
        <div class="dj">DJ ${player?.nickname || 'Unknown'}</div>
      </div>
      ${score !== null ? `<div class="score ${scoreClass}">${score}%</div>` : ''}
      <a class="link" href="https://youtube.com/watch?v=${song.video_id}" target="_blank" rel="noopener">▶</a>
    </div>`;
    }).join('')}
    
    <p class="footer">Generated by 2-Minute DJ • ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>`;
    
    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `2mdj-session-${room.code}.html`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleShareLink = () => {
      const url = `${typeof window !== "undefined" ? window.location.origin : ""}/summary?roomId=${room.id}`;
      setShareUrl(url);
      setShowLinkModal(true);
  };

  const handleNewSession = () => {
    // Clear the stored room from localStorage and redirect to host page
    if (typeof window !== "undefined") {
      localStorage.removeItem("2mdj_host_roomId");
      localStorage.removeItem("2mdj_host_roomCode");
      window.location.href = "/host";
    }
  };

  return (
    <div className="max-w-4xl mx-auto w-full py-12 space-y-12 animate-in fade-in slide-in-from-bottom-8 duration-1000">
      
      {/* Header */}
      <div className="text-center space-y-4">
        <div className="inline-block p-4 rounded-full bg-yellow-500/10 text-yellow-500 mb-2">
            <Trophy size={48} />
        </div>
        <h1 className="text-6xl font-black tracking-tighter">{t("sessionSummary")}</h1>
        <p className="text-neutral-500 text-xl font-medium">
            {playedSongs.length} {t("tracksShared")}
        </p>
      </div>

      {/* Songs List */}
      <div className="bg-neutral-900/50 rounded-[2.5rem] border border-neutral-800 p-8">
        <div className="space-y-4">
            {playedSongs.length === 0 ? (
                <div className="text-center py-12 text-neutral-600 italic">
                    {t("noSongsPlayed")}
                </div>
            ) : (
                playedSongs.map((song, index) => {
                    const score = calculateScore(song.votes);
                    return (
                        <div 
                            key={song.id} 
                            className="group flex items-center justify-between p-4 rounded-2xl bg-neutral-800/30 border border-neutral-700/50 hover:bg-neutral-800 hover:border-indigo-500/50 transition-all"
                        >
                            <div className="flex items-center space-x-4 flex-1 min-w-0">
                                <div className="w-10 h-10 rounded-full bg-neutral-900 flex items-center justify-center text-neutral-500 font-mono text-sm shrink-0">
                                    {index + 1}
                                </div>
                                {/* YouTube Thumbnail */}
                                <img
                                  src={`https://img.youtube.com/vi/${song.video_id}/mqdefault.jpg`}
                                  alt=""
                                  className="w-20 h-14 rounded-lg object-cover bg-neutral-800 shrink-0"
                                  onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }}
                                />
                                <div className="truncate">
                                    <h3 className="font-bold text-lg flex items-center space-x-2">
                                        <span className="truncate">{song.video_title || `${t("unknownTrack")} (${song.video_id})`}</span>
                                        {song.status === "SKIPPED" && (
                                            <span className="text-[10px] uppercase tracking-widest bg-red-500/20 text-red-500 px-2 py-0.5 rounded-full font-bold">{t("skipped")}</span>
                                        )}
                                    </h3>
                                    <p className="text-neutral-500 text-sm font-medium">
                                        DJ { (song as any).player?.nickname || t("unknownDj") }
                                    </p>
                                </div>
                            </div>
                            
                            <div className="flex items-center space-x-4 shrink-0">
                                {score !== null && (
                                    <div className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-lg border ${
                                        score > 75 ? "bg-green-500/10 border-green-500/30 text-green-500" :
                                        score < 25 ? "bg-red-500/10 border-red-500/30 text-red-500" :
                                        "bg-neutral-800 border-neutral-700 text-neutral-400"
                                    }`}>
                                        <ThumbsUp size={14} className={score < 25 ? "rotate-180" : ""} />
                                        <span className="font-mono font-bold">{score}%</span>
                                    </div>
                                )}

                                <a 
                                    href={`https://youtube.com/watch?v=${song.video_id}`}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="p-3 rounded-xl bg-neutral-900 text-neutral-500 group-hover:text-indigo-400 group-hover:bg-indigo-500/10 transition-all"
                                >
                                    <ExternalLink size={20} />
                                </a>
                            </div>
                        </div>
                    );
                })
            )}
        </div>
      </div>

      {/* Action */}
      <div className="flex flex-col sm:flex-row justify-center items-center gap-4 flex-wrap">
        <button 
            onClick={handleNewSession}
            className="flex items-center space-x-2 px-8 py-4 rounded-full bg-white text-black font-bold text-lg hover:bg-neutral-200 transition-all"
        >
            <RotateCcw size={20} />
            <span>{t("newSession")}</span>
        </button>

        <button 
            onClick={handleShareLink}
            className="flex items-center space-x-2 px-8 py-4 rounded-full border border-neutral-700 text-neutral-300 font-bold text-lg hover:bg-neutral-800 transition-all"
        >
            <Share size={20} />
            <span>{t("shareLink")}</span>
        </button>

        <button 
            onClick={handleDownloadJSON}
            className="flex items-center space-x-2 px-8 py-4 rounded-full border border-neutral-700 text-neutral-300 font-bold text-lg hover:bg-neutral-800 transition-all"
        >
            <Download size={20} />
            <span>{t("json")}</span>
        </button>

        <button 
            onClick={handleDownloadHTML}
            className="flex items-center space-x-2 px-8 py-4 rounded-full border border-neutral-700 text-neutral-300 font-bold text-lg hover:bg-neutral-800 transition-all"
        >
            <FileCode size={20} />
            <span>HTML</span>
        </button>
      </div>

      <ShareLinkModal
        isOpen={showLinkModal}
        onClose={() => setShowLinkModal(false)}
        title={language === "de" ? "Link teilen" : "Share Link"}
        link={shareUrl}
        buttonText={t("confirm")}
      />
    </div>
  );
}